import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../../../styles/Home.module.css';

const numList = [1, 2, 3, 4];
const strList = ['one', 'two', 'three'];
const objList = [{ id: 1, name: 'Jane' }];

const Lister: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lister</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1>Lister</h1>
        {numList.map((num) => (
          <p key={num}>{num + 1}</p>
        ))}
        <div>
          {strList.map((str) => (
            <p key={str}>{str}</p>
          ))}
        </div>
        <div>
          {objList.map((obj) => {
            return <p key={obj.id}>{obj.name}</p>;
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Lister;
